### ISSUE TITLE
Uniqueness of entry points for plugins

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-registry#4]
What are the rules and requirements regarding the uniqueness of entry points for registered plugins. Let me describe a use case to illustrate the point. Currently we have the QE plugin:

    "quantumespresso": {
        "name": "aiida-quantumespresso",
        "entry_point": "quantumespresso",
    },

One of the calculations coming with this plugin is of course `quantumespresso.pw:PwCalculation.`
Now I am currently writing a plugin that effectively extends the functionality of the basic Quantum ESPREESO plugin called `aiida-quantumespresso-uscf`, which just like a `quantumespresso.ph:PhCalculation` continues from a `PwCalculation`. Semantically then, it makes sense to place this extension calculation at the entry point `quantumespresso.uscf:UscfCalculation`.
The question is now if this is allowed or would to namespace issues.

I would think at least in principle, that at least as none of the entry points  of the extension plugin clash with those of the base plugin, there should not be a problem. To verify uniquess, we might only have to adapt the format of the registry's json to include a map of *all* the entry points, just as is defined in the plugin's `setup.json`. That is maybe we should have a `plugins.json` that looks something like:

	"quantumespresso": {
	    "name": "aiida-quantumespresso",
	    "entry_points": {
	        "aiida.calculations": [
	            "quantumespresso.ph = aiida_quantumespresso.calculations.ph:PhCalculation",
	            "quantumespresso.pw = aiida_quantumespresso.calculations.pw:PwCalculation"
	        ]
	    }
	},
	"quantumespresso-uscf": {
	    "name": "aiida-quantumespresso-uscf",
	    "entry_points": {
	        "aiida.calculations": [
	            "quantumespresso.uscf = aiida_quantumespresso_uscf.calculations.uscf:UscfCalculation"
	        ]
	    }
	}

**Comment by DropD** [comment]
To clarify: the "entry_point" field really records the root name of entry
points of a plugin (and probably renaming it slightly would be a good idea).

There is a strict uniqueness constraint on actual entry point names, if two
with the same name in the same group are registered none of them will load.

Therefore cross-plugin use of an entry point root name should be limited to
where
* alternatives make appreciably less sense semantically
* both plugin authors agree
* consistent behaviour of entry points with the same root name can be
guaranteed

To make sure i would advise to consider adding something like an extra
"cross_plugin_entry_points" field. It might record complete names to make
it explicit where to file issues in every case.

Consider also that we recomend to keep unrelated plugin classes in separate
plugins, so i think most legitimate use cases will have to do with
extending other plugins.

Also consider that the full entry point map has to be published in the info
file as well, so in theory we can enforce safe entry point naming rules if
it seems necessary.

Do you see other usecases where this approach would not work?

Am 22.06.2017 12:21 schrieb "Sebastiaan Huber" <notifications@github.com>:

**Comment by giovannipizzi** [comment]
Thanks @DropD !
Actually, our use case is the following:
- user A (here: aiidateam) takes ownership of the 'quantumespresso.*' name
- user B (potentially out of the aiida team) wants to develop independently a quantumespresso-related plugin, but for any reason he prefers to work independently from user A (so he doesn't do PRs to A's repository)

In this case, it would be still great to have B's work under quantumespresso.something. Do you agree?
Here, the requirement of locking any 'quantumespresso.*' is in the end too restrictive, maybe.
It's enough to know, for a given complete string, e.g. 'quantumespresso.pw', who "owns" it.

A proposed solution was what Sebastiaan mentioned, i.e. registering (in the "global" registry) all entry points used, rather than just the top name 'quantum espresso'.
Actually one needs a bit less than what originally proposed: probably this is enough for the registry:
```
...
"entry_points": {
        "aiida.calculations": [
            "quantumespresso.ph",
            "quantumespresso.pw"
        ]
    }
...
```
i.e., just the names, not also which class (that instead is written in the setup.py). Note also that we would probably separate the entry points in their namespaces, so different people could register "quantumespresso.pw", one for the plugin and one for the parser, potentially.

The reason to register them all (and not just rely on what's in the setup.py) is that this is the only way to guarantee that the name is taken only once - otherwise two people could work in parallel on two entry points with the same name.

What do you think? Would this approach have major problems?

**Comment by DropD** [comment]
The only problem with this approach is that by only looking at the repo it
looks like you can choose any entry point name, including multiple
different root names.

But sure, we can simply request changes on such pull requests.

Am 22.06.2017 19:10 schrieb "Giovanni Pizzi" <notifications@github.com>:

**Comment by ltalirz** [comment]
> The reason to register them all (and not just rely on what's in the setup.py) is that this is the only way to guarantee that the name is taken only once - otherwise two people could work in parallel on two entry points with the same name.

While this is possible in principle, from a practical point of view, I would say that so far we have not yet encountered issues like these.
On the other hand, if we ask people to duplicate their entry point specification in the plugin registry, I *guarantee* that people will forget to update the registry, when they make changes to their plugin. 
While this could be detected at the next build of the registry, I don't think this is currently worth the effort.

So, for the moment I propose that the build of the registry will print a WARNING whenever it detects that an "entry point root"  is used by multiple plugins.

I think we should still discuss whether reusing the same entry point root for different plugins is really a good idea.
A one-to-one relationship between entry point root and plugin name is easy to remember and to understand. Simplicity is worth preserving, if we can.

In the example of `aiida-quantumespresso-uscf`, there are two alternative solutions to sharing the entry point root:
 * the modifications are worthy to be in a separate plugin. simply use the `quantumespresso_uscf` entry point
 * the modifications don't need to be in a separate plugin. add the functionality directly to `aiida-quantumespresso`

**Comment by ltalirz** [comment]
As discussed in the AiiDA team meeting today:

 * we stick with the [convention laid out in the README](https://github.com/aiidateam/aiida-registry#entry_point_prefix-required)
 * we will warn about cases not following this convention, e.g. like [this](https://github.com/aiidateam/aiida-registry/pull/169#commitcomment-50431984), but
 * we will not strictly enforce the convention in order to enable corner cases where this is deemed acceptable (e.g. if one plugin anyhow plans to merge with another plugin, ...)

Closing...
