### ISSUE TITLE
register aiida-core

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-registry#60]
Once aiida-core 1.0.0b1 is released, register it here

**Comment by ltalirz** [comment]
@giovannipizzi originally I thought we should register aiida-core here, since this will make it easy to show all the entry points it provides.

however, it also makes it more difficult to talk about the plugin registry, since it's no longer just codes/entry points/... provided by plugins.

I'd probably still add it here but I'm also ok to leave it out if others prefer not to. What would you prefer?

**Comment by giovannipizzi** [comment]
Indeed. I was a bit tempted *not* to register it, but I also see that we are still providing in AiiDA core some plugins, so it might be better to do it.

Maybe, though, it's not so bad if we register it - it will end up showing which plugins aiida-core provides (that, by historical reasons, are in side the aiida-core package) so we can still call it a plugin registry.

So, for me, if you want, please go ahead and add it. Maybe I just mention @sphuber if he wants to give his opinion as well.

**Comment by sphuber** [comment]
The only thing that would have been nice maybe is to have the `core.` prefix for the built in calculation plugins, e.g. `core.templatereplacer` instead of the `templatereplacer`, to properly namespace them just like all the other plugins do. This would also be consistent with the naming scheme, i.e. `aiida-plugin` should have `plugin.` as prefix, so `aiida-core` has `core.`. But I am not sure the required changes are worth doing now. Especially since then we should also do this for the data plugins e.g. `aiida.data:structure` -> `aiida.data:core.structure`. Now again, in principle this would have been better, just that we cannot do it now.

That said, maybe we should then hold off with adding `aiida-core` until we have maybe performed these changes for `v2.0.0`? Or do you think that adding them now won't hurt even if we change it down the line?

**Comment by ltalirz** [comment]
I would vote to add it now. I think it's good to have all entry point names in one place.
While I fully agree to move to the `core.` prefix in the future (I'll open an issue), I don't think the current state without the prefix is terribly bad - and it's all the more important to show which prefixes are currently taken.

**Comment by sphuber** [comment]
Ok, agreed
